#################################################################
#Solax
# You must replace XXXXXXXXX with your own solax registration number
# You must replace the static IP with your own
# Battery warming added
#################################################################
solax_local_ip: http://192.168.xxx.xxx/ # IP of solax module

solax_local_realtime_payload: "optType=ReadRealTimeData&pwd=YYYYYYYYYY"
solax_local_settings_payload: "optType=ReadSetData&pwd=YYYYYYYYYY"
solax_local_set_selfuse_battery_min_soc_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":29,"val":"{{ level }}"}]}'
solax_local_set_feedin_battery_min_soc_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":32,"val":"{{ level }}"}]}'
solax_local_set_feedin_battery_grid_charge_level_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":33,"val":"{{ level }}"}]}'
solax_local_set_period2_enable_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":41,"val":"{{ enabled }}"}]}'
solax_local_set_selfuse_charge_from_grid_enable_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":30,"val":"{{ enabled }}"}]}'
solax_local_set_selfuse_battery_grid_charge_level_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":31,"val":"{{ level }}"}]}'
solax_local_set_inverter_mode: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":28,"val":"{{ value }}"}]}'
solax_local_set_manual_mode_behaviour: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":36,"val":"{{ value }}"}]}'
solax_local_set_battery_forced_charge_start: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":37,"val":"{{ value }}"}]}'
solax_local_set_battery_forced_charge_stop: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":38,"val":"{{ value }}"}]}'
solax_local_set_battery_forced_charge_start2: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":42,"val":"{{ value }}"}]}'
solax_local_set_battery_forced_charge_stop2: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":43,"val":"{{ value }}"}]}'
solax_local_set_allowed_discharge_start: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":39,"val":"{{ value }}"}]}'
solax_local_set_allowed_discharge_end: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":40,"val":"{{ value }}"}]}'
solax_local_set_heat_enable_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":116,"val":"{{ enabled }}"}]}'
solax_local_set_heat_start_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":117,"val":"{{ value }}"}]}'
solax_local_set_heat_stop_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":118,"val":"{{ value }}"}]}'
solax_local_set_heat_start2_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":119,"val":"{{ value }}"}]}'
solax_local_set_heat_stop2_payload: 'optType=setReg&pwd=YYYYYYYYYY&data={"num":1,"Data":[{"reg":120,"val":"{{ value }}"}]}'
