solax_zappi_octopus_notifications_input_button:
  input_button:
    # Reset Solax Zappi Octopus notification Exclusions
    solax_zappi_octopus_reset_notification_exclusions:
      name: Reset Notification Exclusions
      icon: mdi:button-pointer

    # Reset Solax Zappi Octopus Mobile List
    solax_zappi_octopus_reset_device_list:
      name: Reset Device List
      icon: mdi:button-pointer
