##############################################################
#
# offset:
#   days: 2 <---- update to your billing day (2 if your bills start on the 3rd)
#
##############################################################
# v10.2.0 Battery heating power
# v6.0.0 utility meter for solax
##############################################################

solax_zappi_octopus_utilitymeter:
  utility_meter:
    ##########################################################
    # PV Generation
    ##########################################################
    daily_solar:
      unique_id: 91154042-717c-42f0-ab5a-3b49eee360d0
      source: sensor.solar_panels_energy
      name: Daily Solar Gen
      cycle: daily

    monthly_solar:
      unique_id: 6c6ecf87-510f-4b69-8cd7-20108fc6f800
      source: sensor.solar_panels_energy
      name: Monthly Solar Gen
      cycle: monthly
      offset:
        days: 2

    ##########################################################
    # Actual yield (net of solar & battery in/out)
    ##########################################################
    daily_inverter:
      unique_id: 0b888b17-2ca0-4b79-90bb-43c98c47199f
      source: sensor.solax_local_inverter_aggregated_energy
      name: Daily Yield
      cycle: daily
      net_consumption: true

    monthly_inverter:
      unique_id: f7c252ac-5367-4fc5-bbb5-06949d5a3a68
      source: sensor.solax_local_inverter_aggregated_energy
      name: Monthly Yield
      cycle: monthly
      net_consumption: true
      offset:
        days: 2
    ##########################################################

    ##########################################################
    # Total load
    ##########################################################
    daily_load:
      unique_id: f88ebe90-536f-4978-ad26-486825890e3a
      source: sensor.solax_local_load_aggregated_energy
      name: Daily Use
      cycle: daily

    monthly_load:
      unique_id: 82db8bd0-02d2-4cb3-94c2-a8c25e949086
      source: sensor.solax_local_load_aggregated_energy
      name: Monthly Used
      cycle: monthly
      offset:
        days: 2
    ##########################################################

    ##########################################################
    # House load
    ##########################################################
    daily_house_load:
      unique_id: e028afa2-8d86-4504-a107-8212306082dd
      source: sensor.solax_local_house_load_aggregated_energy
      name: Daily House Used
      cycle: daily

    monthly_house_load:
      unique_id: 2cf0b05d-def6-4955-a8bb-12293de735ae
      source: sensor.solax_local_house_load_aggregated_energy
      name: Monthly House Used
      cycle: monthly
      offset:
        days: 2
    ##########################################################

    daily_self_consumed:
      unique_id: 742374d5-2686-407c-b57d-c824f0b58636
      source: sensor.solax_local_self_consumption_aggregated_energy
      name: Daily Self Consumed
      cycle: daily

    monthly_self_consumed:
      unique_id: a6117dff-c471-4b49-a847-d88508e1c25b
      source: sensor.solax_local_self_consumption_aggregated_energy
      name: Monthly Self Consumed
      cycle: monthly
      offset:
        days: 2
    ##########################################################

    ##########################################################
    # Import Meters
    ##########################################################
    daily_grid_used:
      unique_id: 0f7a5ac1-e0ea-4106-82e0-bca9c5196b4d
      source: sensor.solax_local_grid_used_aggregated_energy
      name: Daily Grid Used
      cycle: daily

    daily_grid_import:
      unique_id: adb5e49f-34f5-4980-b776-c17d240b01f1
      source: sensor.solax_local_grid_used_aggregated_energy
      name: Daily In From Grid
      cycle: daily
      tariffs:
        - peak
        - offpeak
        - free

    monthly_grid_import:
      unique_id: 252fb654-eef6-4d8e-ada3-b358e7493e0b
      source: sensor.solax_local_grid_used_aggregated_energy
      name: Monthly In From Grid
      cycle: monthly
      offset:
        days: 2
      tariffs:
        - peak
        - offpeak
        - free

    ##########################################################
    # Battery Storage Meters
    ##########################################################
    daily_grid_ac_stored:
      unique_id: 63db6613-5e94-4491-b395-068f46609a4b
      source: sensor.solax_local_inverter_in_aggregated_energy
      name: Daily Grid AC Stored
      cycle: daily

    monthly_grid_ac_stored:
      unique_id: a6892fe5-0de5-4020-b2ed-4ad493ec0f17
      source: sensor.solax_local_inverter_in_aggregated_energy
      name: Monthly Grid AC Stored
      cycle: monthly
      offset:
        days: 2

    daily_total_stored:
      unique_id: 5ac3f1f7-0551-4228-a005-fdb62eb0e260
      source: sensor.solax_local_battery_in_aggregated_energy
      name: Daily Total Stored
      cycle: daily

    monthly_total_stored:
      unique_id: c59d79e1-8bd6-4767-b5de-a1fdfa18930a
      source: sensor.solax_local_battery_in_aggregated_energy
      name: Monthly Total Stored
      cycle: monthly
      offset:
        days: 2

    daily_grid_stored:
      unique_id: 6fd43d8e-fe8e-41a0-9d8d-db0ad3771e97
      source: sensor.solax_local_battery_in_from_grid_aggregated_energy
      name: Daily Grid Stored
      cycle: daily

    monthly_grid_stored:
      unique_id: 5f2b788b-54ca-4ccb-b5fb-074ad96dce7e
      source: sensor.solax_local_battery_in_from_grid_aggregated_energy
      name: Monthly Grid Stored
      cycle: monthly
      offset:
        days: 2

    daily_solar_stored:
      unique_id: f89aa88b-9782-4267-854b-007ead4fc23d
      source: sensor.solax_local_battery_in_from_solar_aggregated_energy
      name: Daily Solar Stored
      cycle: daily

    monthly_solar_stored:
      unique_id: 1667840a-0d28-42d2-954c-a92ad1ceae8c
      source: sensor.solax_local_battery_in_from_solar_aggregated_energy
      name: Monthly Solar Stored
      cycle: monthly
      offset:
        days: 2

    ##########################################################

    ##########################################################
    # Battery Use Meters
    ##########################################################
    daily_battery_use:
      unique_id: 04835631-15ae-403d-b968-54c76f468ad5
      source: sensor.solax_local_battery_out_aggregated_energy
      name: Daily Battery Use
      cycle: daily

    monthly_battery_use:
      unique_id: 411d9019-f856-461b-86f3-b877e4be3a46
      source: sensor.solax_local_battery_out_aggregated_energy
      name: Monthly Battery Use
      cycle: monthly
      offset:
        days: 2
    ##########################################################

    ##########################################################
    #Battery Export Meters
    ##########################################################
    daily_manual_battery_export:
      unique_id: 00e17fbd-6256-4cc0-91cc-1df7422ac124
      source: sensor.solax_local_battery_dump_aggregated_energy
      name: Daily Manual Battery Export
      cycle: daily

    monthly_manual_battery_export:
      unique_id: ef152f56-fc35-4666-bda6-d7cef6d2044c
      source: sensor.solax_local_battery_dump_aggregated_energy
      name: Monthly Manual Battery Export
      cycle: monthly
      net_consumption: false
      delta_values: false
      periodically_resetting: true
      always_available: false
      offset:
        days: 2
    ##########################################################

    ##########################################################
    #Export Meters
    ##########################################################
    # daily_grid_fed:
    #   unique_id: 498a8be5-d788-410b-a687-4e4b084fc99e
    #   source: sensor.solax_local_grid_export_aggregated_energy
    #   name: Daily Grid Fed
    #   cycle: daily

    export_daily:
      unique_id: 2bbaf57b-73f2-4a41-83b3-0bceb2f0dbd3
      source: sensor.solax_local_grid_export_aggregated_energy
      name: Daily Export
      cycle: daily
      net_consumption: false
      delta_values: false
      periodically_resetting: true
      always_available: false

    export_monthly:
      unique_id: 04c30247-b9a2-42a7-bf20-19f1a10d2281
      source: sensor.solax_local_grid_export_aggregated_energy
      name: Monthly Export
      cycle: monthly
      net_consumption: false
      delta_values: false
      periodically_resetting: true
      always_available: false
      offset:
        days: 2
    ##########################################################

    battery_heating_daily:
      unique_id: 0c931384-f9b5-4b4b-ade5-3f3a896e4836
      source: sensor.solax_local_battery_heating_aggregated_energy
      name: Daily Battery Heating
      cycle: daily
      net_consumption: false
      delta_values: false
      periodically_resetting: true
      always_available: false

    battery_heating_monthly:
      unique_id: b7a2a01a-6d4f-46df-9b26-5fd212ce1d69
      source: sensor.solax_local_battery_heating_aggregated_energy
      name: Monthly Battery Heating
      cycle: monthly
      net_consumption: false
      delta_values: false
      periodically_resetting: true
      always_available: false
      offset:
        days: 2
