octopus_dispatches_input_number:
  input_number:
    limit_ev_kwh_charge_target:
      name: Limit EV Charge Target
      unit_of_measurement: "kWh"
      min: 20
      max: 42
      mode: box
      step: 0.5
      icon: mdi:meter-electric-outline
    zappi_charging_minutes:
      name: Zappi Charging Minutes
      min: 0
      max: 100000
      step: 1
    zappi_charging_minutes_6hr_limit:
      name: Zappi Charging Minutes 6hr Limit
      min: 0
      max: 100000
      step: 1