octopus_dispatches_input_number:
  input_number:
    octopus_intelligent_total_dispatch:
      name: Octopus Intelligent Total Dispatch
      min: 0
      max: 200
      step: 0.1
      mode: box
      icon: mdi:ev-station
      unit_of_measurement: "kWh"
    limit_ev_kwh_charge_target:
      name: Limit EV Dispatch Target
      unit_of_measurement: "kWh"
      min: 20
      max: 42
      mode: box
      step: 0.5
      icon: mdi:meter-electric-outline
    estimated_charging_losses:
      name: Charging Loss Factor
      unit_of_measurement: "%"
      max: 15
      min: 0
      step: 0.25
      mode: box
      icon: mdi:percent
    zappi_charging_minutes:
      name: Zappi Charging Minutes
      min: 0
      max: 100000
      step: 1
    zappi_charging_minutes_6hr_limit:
      name: Zappi Charging Minutes 6hr Limit
      min: 0
      max: 100000
      step: 1
    # ev_battery size (not used anymore)
    ev_battery_size:
      name: Registered EV Battery Size
      unit_of_measurement: "kWh"
      min: 10
      max: 200
      step: 1
      mode: box
      icon: mdi:car-battery
    # Delay automation when EV first connected
    delay_when_ev_connected:
      name: Delay after EV is Connected
      unit_of_measurement: "minutes"
      min: 1
      max: 15
      step: 1
      mode: box
      icon: mdi:car-clock
    # SoC must be less than to engage companion charge
    companion_charge_soc_distance_lte:
      name: SoC Distance is L.T.E
      unit_of_measurement: "%"
      min: 5
      max: 95
      step: 1
      mode: box
      icon: mdi:battery-10
    # SoC must be less than to engage companion charge
    companion_worth_it:
      name: Worth IT - Time left in HH
      unit_of_measurement: "minutes"
      min: 5
      max: 25
      step: 1
      mode: box
      icon: mdi:timer-plus