octopus_dispatches_input_datetime:
  input_datetime:
    charging_24hr_allowance:
      name: Charging 24hr Allowance
      has_date: true
      has_time: true
      icon: mdi:timer-plus-outline
    #Time that ev can start charge +/- wobble
    don_t_charge_ev_before_time:
      name: Smart Charge After
      has_date: false
      has_time: true
