octopus_dispatches_input_number:
  input_number:
    octopus_intelligent_total_dispatch:
      name: Octopus Intelligent Total Dispatch
      min: 0
      max: 200
      step: 0.1
      mode: box
      icon: mdi:ev-station
      unit_of_measurement: "kWh"
    limit_ev_kwh_charge_target:
      name: Limit EV Charge Target
      unit_of_measurement: "kWh"
      min: 20
      max: 42
      mode: box
      step: 0.5
      icon: mdi:meter-electric-outline
    zappi_charging_minutes:
      name: Zappi Charging Minutes
      min: 0
      max: 100000
      step: 1
    zappi_charging_minutes_6hr_limit:
      name: Zappi Charging Minutes 6hr Limit
      min: 0
      max: 100000
      step: 1
    # ev_battery size (not used anymore)
    ev_battery_size:
      name: Registered EV Battery Size
      unit_of_measurement: "kWh"
      min: 10
      max: 200
      step: 1
      mode: box
      icon: mdi:car-battery
    # Delay automation when EV first connected
    delay_when_ev_connected:
      name: Delay after EV is Connected
      unit_of_measurement: "minutes"
      min: 1
      max: 15
      step: 1
      mode: box
      icon: mdi:car-clock