
##############################################################
# v9.0.0 utility meter for IOG changes to restrict off peak tariff to 6hrs
##############################################################

octopus_dispatches_utilitymeter:
  utility_meter:
    charge_time_24hr_allowance:
      unique_id: dd44b78f-2708-4fba-bb3e-ad83c4c01fb9
      source: input_number.zappi_charging_minutes
      name: Charge Time 24hr Allowance



# Track how close you are to maximum assuming 6 x 7kWh. 
# Allows for a rough approximation of percentage required when initiallising the charge session 
    charge_kwh_24hr_allowance:
      unique_id: 5dcc45bd-7181-42ae-8890-9b0492feece9
      source: sensor.zappi_charge_added_session
      name: Charge kWh 24hr Allowance


    ##########################################################

