battery_budget_input_select:
  input_select:
    slot_start:
      name: Start Time
      options:
        - "04:00"
        - "04:15"
        - "04:30"
        - "04:45"
        - "05:00"
        - "05:15"
        - "05:30"
        - "05:45"
        - "06:00"
        - "06:15"
        - "06:30"
        - "06:45"
        - "07:00"
        - "07:15"
      icon: mdi:clock-start
    slot_end:
      name: End Time
      options:
        - "22:00"
        - "22:15"
        - "22:30"
        - "22:45"
        - "23:00"
        - "23:15"
        - "23:30"
        - "23:45"
      icon: mdi:clock-end
    slot_interval:
      name: Interval
      options:
        - 15
        - 30
        - 60
      icon: mdi:timer-cog-outline








