battery_budget_input_number:
  input_number:
    power_stat_avg_days:
      name: "Number of Days"
      initial: 10
      min: 1
      max: 10
      step: 1
      mode: box
      icon: mdi:calendar
    typical_house_power:
      name: Typical House Power
      min: 0.000
      max: 2.000
      step: 0.001
      mode: box
      icon: mdi:transmission-tower-import
      unit_of_measurement: "kW" 
    hours_of_reserve_energy:
      name: Hours of Reserve Energy
      min: 0
      max: 24
      step: 0.25
      mode: box
      icon: mdi:clock-star-four-points-outline
      unit_of_measurement: "hr"
    additional_reserve_soc:
      name: Additional Reserve Soc
      min: 0
      max: 10
      step: 1
      mode: box
      icon: mdi:battery-10
      unit_of_measurement: "%"