solax_zappi_octopus_ui_input_boolean:
  input_boolean:
    ###########################################
    # Solax Zappi Octopus UI
    # v9.2.0 Refactored out things that didn't belong
    ###########################################
    #Solax automation running indicator
    solax_automation_running:
      name: Solax Automation Running
      icon: mdi:robot-angry
    solax_octopus_hide_settings:
      name: Hide Settings
      icon: mdi:eye-off
    solax_octopus_hide_energy:
      name: Hide Energy Charts
      icon: mdi:eye-off
    solax_octopus_hide_power:
      name: Hide Power Charts
      icon: mdi:eye-off
    solax_octopus_hide_stats:
      name: Hide Stats Charts
      icon: mdi:eye-off
    battery_reserve_show_hide:
      name: Show/Hide Info
      icon: mdi:eye-off
    battery_export_show_hide:
      name: Export Details Show/Hide
      icon: mdi:eye-off
    daily_export_show_hide:
      name: Daily Show/Hide
      icon: mdi:eye-off
    nightly_export_show_hide:
      name: Nightly Exports Show/Hide
      icon: mdi:eye-off
    gap_export_show_hide:
      name: Gap Exports Show/Hide
      icon: mdi:eye-off
    inverter_modes_show_hide:
      name: Show/Hide Work Mode
      icon: mdi:eye-off
    inverter_settings_show_hide:
      name: Show/Hide Settings
      icon: mdi:eye-off
    inverter_default_behaviours_show_hide:
      name: Show/Hide Default Behaviours
      icon: mdi:eye-off
    inverter_and_battery_show_hide:
      name: Show/Hide Inverter and Battery
      icon: mdi:eye-off
    battery_soh_show_hide:
      name: Hide Battery SoH Charts
      icon: mdi:eye-off
    battery_voltage_show_hide:
      name: Show/Hide Battery Voltage Charts
      icon: mdi:eye-off
    ev_charging_show_hide:
      name: Show/Hide EV Charging Charts
      icon: mdi:eye-off
    ###########################################
