#############################################
# v1.0 octoplus_sessions_input_boolean
#############################################
octoplus_sessions_input_boolean:
  input_boolean:
    # When there is an octopus free electric session, to prepare on the day, user can choose to set
    # a target SoC for which to discharge the battery to at a certain time, or, by using this switch the battery will
    # only be charged to the target SoC.
    octopus_free_electric_soc_use:
      name: Use Target SoC as Charge to Soc
      icon: mdi:transmission-tower-import
    free_electric:
      name: free_electric
      icon: mdi:light-switch
